apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-kube-state-metrics
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: flux-system