apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    envFromSecret: grafana-oidc-secret
    grafana.ini:
      server:
        root_url: https://grafana.sshme.in/
      auth.generic_oauth:
        enabled: true
        name: "OIDC"
        allow_sign_up: true
        client_id: grafana
        auth_url: https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/auth
        token_url: https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/token
        api_url: ttps://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/userinfo
        scopes: "openid email profile"
        auto_login: true         
      auth:
        disable_login_form: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: PROMETHEUS
            type: prometheus
            access: proxy
            url: http://prometheus-server
            isDefault: true
    sidecar:
      dashboards:
        enabled: true

    

    