apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - outline-release.yaml
  - route.yaml
  - minio-outline-secret.yaml
 # - postgres-outline-password-secret.yaml
