apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssh-me-in-certificate
spec:
  secretName: ssh-me-in-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - "*.sshme.in"