apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:93ufuKRNolPNP51rweCSiCAY0+JdXnvE203JmnyY4VY=,iv:Qsx4PTJr0BFcys1k00W9P1OxhXvMUOu4cjE4X9YP9yI=,tag:vuy1usq7auYj90E+vjm/lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON3o5VStiNFFpaTljRFBn
            dnZPOGlyZ25uSWZNdUtGNCtxbWVEc0g3NndFClZMWHlUZ21Cc0t5bHVyTmdCWWhl
            ZUltQzQwMnhobURlOEt3WHI3djJNd2cKLS0tIE9DaC8ya3BGQ0dHcEc0NTlkN0c2
            dlZ5UUdEdC9MMG1Ub1FWTW1xdSsxRlkKYWL5AmMNM0XxfV8Vgm7C/TKsFL9Z5ZjN
            M0KGKeTtV8F5k5meAoNEpfwx+aEm2RE4IA1se1lvN0m0zkfkXQxb6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T10:38:35Z"
    mac: ENC[AES256_GCM,data:+xCHIu0lsJ2D6W0TQScCVW30213Ti4y7nbzpy9Acb7H0cami05TNIxLPF9CHaVOH/mBzD/4Q8+X6GSfg682cVXkSZYa3LquhANCJhtPitblwRR5jJ8c7rV9OnuulV+y81oeXdsPm9ppItig9p7azvDW6HP32/YrmDsg7kDGAPik=,iv:r1id2RSvbZUKGUX6Qs4xIYq6+NCpdOMAiidCX5IEJks=,tag:eaSLqevkAfsDN+9lLd6OAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
