apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    extraSecretMounts:
      - name: grafana-influx-password
        secretName: grafana-influx-password
        mountPath: /etc/grafana-secrets
        readOnly: true
      - name: influx-token
        secretName: influx-v2-token-secret
        mountPath: /etc/influx-secrets
        readOnly: true
    envFromSecret: grafana-oidc-secret
    grafana.ini:
      server:
        root_url: https://grafana.sshme.in/
      auth.generic_oauth:
        enabled: true
        name: "OIDC"
        allow_sign_up: true
        client_id: grafana
        auth_url: https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/auth
        token_url: https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/token
        api_url: ttps://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/userinfo
        scopes: "openid email profile"
        auto_login: true
        role_attribute_path: contains(groups[*], 'k8s-admin') && 'Admin' || 'Viewer'         
      auth:
        disable_login_form: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: PROMETHEUS
            type: prometheus
            access: proxy
            url:  "http://prometheus-kube-prometheus-prometheus:9090"
            isDefault: true
          - name: influx
            type: influxdb
            access: proxy
            url: "http://influx-influxdb.storage.svc.cluster.local:8086"
            database: opnsense
            user: opnsense
            jsonData:
              httpMode: POST
            secureJsonData:
              password: $__file{/etc/grafana-secrets/influx-password}
          - name: InfluxDB v2
            type: influxdb
            access: proxy
            url: "http://influxv2-influxdb2.storage.svc.cluster.local:80"
            jsonData:
              version: Flux
              organization: "influxdata"
              defaultBucket: "default"
              timeInterval: "10s"
            secureJsonData:
              token: $__file{/etc/influx-secrets/influx-token}
    sidecar:
      dashboards:
        enabled: true
