apiVersion: v1
kind: Secret
metadata:
    name: influx-v2-token-secret
type: Opaque
stringData:
    influx-token: ENC[AES256_GCM,data:WwB8JyTQGvsEwBED/YXglTLCqhxJh8oeNg==,iv:37nxmhOTPXAiOoZsS+L97i/oe5jNBlvA7JuVssYriQ0=,tag:Wi3ei2ZUV3+0O8cCsOo6zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VHlBOXVBd25nbDVTdGtx
            cXhOdGRMNEdIejcvSGUwR0lEYkNyOTZWK1VFClJWRnE3ZThrM2FjaXIyNkJtL1lR
            b0pZZHZhUG1McEwwNy9nanVaSlZjT2cKLS0tIFErUG4vTjBzTDZJVmNFMG45a2di
            NWNINTBkVG50S3pzWEZDK0hWMzJGaVkKVyjeDw3SqhMqfhtq8VbAQMkryRrdsYW6
            x2v3FJi27jgmWe0d6KPfN/6+/3bmGmt3qVk8VisPVZcTln5f8pbdAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T07:53:57Z"
    mac: ENC[AES256_GCM,data:HC5l/vCrD6T5aF8Cbb+5ZPSE+Ljayil01n7Ktz2G73ekIUaunifH1Vesl9rnxe4Imw8Vs59K656bgkq3bZFaWfcqmYaLFwIp9KRonf1LlhF8rxknAkvHAvml/0rzgSur+yqwu39zJr2QGGoFg8eFJwOZkMEiKsiYJgYHgW9UYZw=,iv:F0JZVeaNpcrN177QqKiEwYYM8EnPAliHj/+BZLOT6EA=,tag:iIBN6qpB0fLJezkAXvQ/BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
