apiVersion: v1
kind: Secret
metadata:
    name: grafana-influx-password
type: Opaque
stringData:
    influx-password: ENC[AES256_GCM,data:d1pYY1B6CF0PybdyzNj3InJOVHmC7czrow==,iv:h2KeZSzlTbCx5BZSDB4LvQ/b0/HAEKWIIwh3NyxMdKI=,tag:FIzFRI/k2oI47Z8pXLHA5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UzJQZUYzSFVmWGF3dUY2
            VjNvNlNVNDUyejZqWVQ5NDhCbXBNd1RUYmdNCmhZelNOQ1ZUalpUSjJIa2lnMVhV
            c2pMVkhUSUFyS3RicjlTR3lVVUtreE0KLS0tIGhHZ0FwNmtNbWZlTGp5eWRXL2tH
            Z2lKTWxsVWxLKzFaY3psYzdXd2F2U2cKhBTyeVuBK7vSadpnHQLG0uUyd7oXX4xV
            ED6HUHPdZgZMSVjVOLQmVpdA3410vBFJc4qE1oD88M/LtZ4Zn/4mgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T19:32:19Z"
    mac: ENC[AES256_GCM,data:9MBQ+fBWveWzuC1mXk8WlmxT7V54O3SwemfmvLT76+NSEii6n2/RdqblHQww7dfYv3FQ01X9yTihwylNaSZGM0IJy7gsi2yxrghnCW3TuCtMW/t6xGxPAe7YEriLAT349yL90pp+WNGNuVI2k/dRreYcz3/IaFP7k8kgrJffuVY=,iv:C4fWhjHUxoXEsBWiQLqSyjeqPMp4C6xl1al/IYIQW/w=,tag:zdGTNZ+VecgXHORiyBfd6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
