apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-release.yaml
  - route.yaml
  - grafana-oidc-secret.yaml
  - influx-password-secret.yaml
  - dashboards