apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana-route
  annotations:
    gethomepage.dev/href: "https://grafana.sshme.in"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Cluster Dashboard
    gethomepage.dev/group: Infra
    gethomepage.dev/icon: https://www.svgrepo.com/show/448228/grafana.svg
    gethomepage.dev/app: grafana-route
    gethomepage.dev/name: Grafana
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: default-gateway
      namespace: istio-ingress
  hostnames:
    - grafana.sshme.in
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana
          port: 80