apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops-age-storage
  namespace: flux-system
spec:
  interval: 1m
  path: ./shared/secrets
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system