apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - base.yaml
  - istiod.yaml
  - ztunnel.yaml
  - node-agent.yaml
  - istio-system-namespace.yaml
  - kiali-release.yaml
  - route.yaml
  - grafana-sa-secret.yaml
  - ztunnel-scrape.yaml
  - service-entries.yaml