kind: Secret
apiVersion: v1
metadata:
    name: postgres-config-keycloak
data:
    database: ENC[AES256_GCM,data:p0UMe7Z2bowcji75,iv:1F/c449gPWz+RTRNCDr0Q2uIXTC/6KRyRQMeXgXyBbQ=,tag:ZVzbLUUmgIHd6FJHavlEMw==,type:str]
    host: ENC[AES256_GCM,data:uaWCI3n1eA8i9SXpONGJ0w==,iv:lNJ7Rge13BMAOWbdGEJZmBLKLLl+RHqPjfitR7+qxZs=,tag:WtieLEFHgwpZeEZa6Kkanw==,type:str]
    password: ENC[AES256_GCM,data:tIl/u7j9GOV6KOUEA5tJj4e/V5jxs3IhMepFxw==,iv:yySRIAvogC8Ntj18NlzUBLDLorQ++pdasH3PX9xJsPk=,tag:Lwb/e6VAouSfYd5fJlmyBw==,type:str]
    port: ENC[AES256_GCM,data:bCeZMB2m7/o=,iv:ruZLMuQw/ToT5Gr0YOie4YY9bessKbsLLf4s+hfl4YY=,tag:h2lp+AxG+d4qTQzlHHKpeA==,type:str]
    user: ENC[AES256_GCM,data:KWJQNYVkpyeiJ3PNgE1SKoLgB9g=,iv:0FjlRmbiRbaAY7XevEhinBSZIcRAIQ+lDAN6EOzWf84=,tag:8BkZ0B6dyGYr4WqL2XGNlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTVNVQnVaSG5NUXFRSFNr
            T0VjamRKM2VHWWhlU3RLaFVwODFML0pKS25JCk5EdDdmbzB2UjJpOUdURnVGVFU2
            Z2FXSkhVRUFicG1zQWlkVlZxWjA5VjQKLS0tIFZGeWxzQUd6ZWV5VG1wRVBMdnRX
            OHVqejZhdDNZT0NtYkE2VHFyeHk1ODgKBlHj97BZxzu4QGr5Jl8cZS2ZQyGt4zZJ
            e3rOBxTcBXVZcLFaI7uabTjxHIh+yJccLfU3GeinMsRWRHKcRx5/1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T21:28:06Z"
    mac: ENC[AES256_GCM,data:DcJk24t+Zc2GtTmSOftrGVEUTN2KxSjsS4PBEPYMGpAop+nmj8wa9hmt/ymFFHAkbOTRwuoRlYarjvMHm3KyCFptof4LSZuaBHfvAuNGKPXkjkr7+LSRpRK+CX9yQLagEH7q4cm+amsSbPU+J1ahR8BssCS0dvNPTX16crOavuw=,iv:4KNZqQBVxvAQ/BgsDwqzON0qpz20ODCYqYcUJb+FI70=,tag:GCaDWOhLomU5TCOKHUOOHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
