kind: Secret
apiVersion: v1
metadata:
    name: postgres-config-keycloak
data:
    database: ENC[AES256_GCM,data:gGdvph3sqEDS6Mzj,iv:BJHgUg17PcsL061tpcB72+LT8Tgx2Mdc1wcHRPrZpxE=,tag:noDzxKRqSsOKszcpy3QGVQ==,type:str]
    host: ENC[AES256_GCM,data:DvurveIMNUam26pXS4D9Q7vjZZao/q29,iv:cBcw3CckVbL2PbNMbnGRLbMPzo8IIo8Vu2JitIk+x5o=,tag:GE4qVE/vVY/0IBpSyP/wLA==,type:str]
    password: ENC[AES256_GCM,data:KTTeBuFcyHGT1ptE5RBUo46Mvs6z6RSzlPjkEQ==,iv:9Mq8EroLFCiEJODUk7nPM2oC7rhGm7hvMPLWqvUWbOw=,tag:1FTRpwchgQnBBWrjNtsSNQ==,type:str]
    port: ENC[AES256_GCM,data:/2VqCLYrSTA=,iv:jFS+H4QH+1W+XFgQGdzPM+AoQgs8NOgXjx51kcacG/w=,tag:yFegnybKR3s/tdIRS1kMuw==,type:str]
    user: ENC[AES256_GCM,data:AFYl5oAFJDp70CrTl1/rkQJ3k0c=,iv:NVLI900JrzSRYpnn4bU1ZozrjIfWKAAMyYKiwiYNr2s=,tag:4AN5dM+lLVOppV+vViYOyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaHYrS0dPUjB4dzVsWDU3
            RHJpOHhOS1JvcUVrM083dVhOb2NWcWJ2M1RnCnVEOThyZHFJYjhoRVNzU3ZCdUxQ
            MmxpcGZZZ09aMUxZRDBYYTd2U0tpM1UKLS0tIEF4UGJCZVRUM0cxdUQwMGV1T0sv
            V1BGdGpVa3VYOGpMNXNHY1EvR0taa1EKoiq35yPp2NRkOLvuEPzL7bSog2Xhp0yp
            5Sf6IMQ486r8xizut/NG/qYL0wh7UvTxJ9wgpAjN/qvq45rnd8tgow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T21:36:36Z"
    mac: ENC[AES256_GCM,data:fSqRlkZEopF8hZCbcKDNVxj8zu8DyTKzVX8e119glm55+1iIi00u+BrBX5EX7dRpvTw318BSCNKFVGf+9tuep8+/FZtqq9alzTwZvE5252EgglMREs2qD3wNSK2FL0J6JnWQvTCv4ChvTNEKzekk8v0XzwIcKrfFJsckgbu6P8M=,iv:fTNPSisbAzvJWIC9igVB9xOwfYGBgwokHa6/QGkiDzQ=,tag:wStkoItOHtgn/F/HA3tkzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
