apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress
resources:
  - default-gateway.yaml
  - sshme-certificate.yaml
  - http-redirect.yaml
  - istio-ingress-namespace.yaml
  - permis.yaml
