apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - namespace.yaml
  #- waypoint.yaml
  - service-entry.yaml
  - sa.yaml
  - coder
  - grocy
  - headlamp
  - homepage
  - keycloak
  - outline
  
