apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: PLACEHOLDER
  namespace: flux-system
spec:
  interval: 1m
  path: PLACEHOLDER
  prune: true
  targetNamespace: PLACEHOLDER
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-system
