#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: storage
#  namespace: storage
#spec:
#  interval: 1m
#  path: ./sshme-in/storage
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  targetNamespace: storage
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age 
  
#---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-source
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age