apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: disable-mtls-prometheus
spec:
  host: prometheus-server.monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
