apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - istio.yaml
  - nextcloud.yaml
  - jetstack.yaml
  - bitnami.yaml
  - coder.yaml
  - community-charts.yaml
  - headlamp.yaml
  - external-secrets.yaml