apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  path: ./sshme-in/charts
  prune: true
  targetNamespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-system
