apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../config
  - grafana
  - prometheus

patches:
  - target:
      kind: Namespace
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: monitoring
  - target:
      kind: Kustomization
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: monitoring
      - op: replace
        path: /spec/path
        value: ./monitoring
      - op: replace
        path: /spec/targetNamespace
        value: monitoring
